### ISSUE TITLE
Time clock digts seem too apart

### ISSUE THREAD

**Issue by mydegeneration** [zagortenay333/ciliora-tertia-shell#3] opened 2015-06-30 01:46 UTC
![screenshot from 2015-06-29 21-45-04](https://cloud.githubusercontent.com/assets/7192681/8422351/32e9ba26-1ea8-11e5-9255-26abc1a729be.png)

Are the clock digits supposed to be this apart? I'm using your latest code on Fedora 22

**Comment by zagortenay333** [comment] 2015-06-30 08:35
Weird. I don't have this, and I'm on fed22 as well.

What are you using for font rendering improvements? Maybe that's the culprit. I'm using Ozon's font config: https://github.com/ozonos/ozon-packaging/tree/master/SRPMS/22

**Comment by mydegeneration** [comment] 2015-06-30 13:14
I used Fedy for font rendering which I presume uses Ozon's font config but I could be wrong.

**Comment by zagortenay333** [comment] 2015-06-30 13:30
Gonna close this for now. I can't reproduce it, and I doubt it has anything to do with the shell theme either.

Btw, do you have Droid-Sans installed on your system? It's default font for this theme.

**Closed by zagortenay333** 2015-06-30 13:30 UTC

**Comment by mydegeneration** [comment] 2015-06-30 13:32
It might be that. Will check when I get home.

**Comment by mydegeneration** [comment] 2015-06-30 23:43
I do have Droid-Sans installed. Also, I tried reverting the fontconfig from Fedy and the bug is still there.

**Comment by zagortenay333** [comment] 2015-07-01 09:19
Hmm... I'm out of ideas. Does it happen with other themes too? Did you try to change the font inside the `gnome-shell.css` file?

**Comment by mydegeneration** [comment] 2015-07-02 23:09
Yeah it's the Droid Sans font. I switched it to Cantarell and the clock digits appear normal. Switched it back to Droid Sans and clock digits appear apart again.

**Comment by mydegeneration** [comment] 2015-07-03 20:21
I just fired up a VM with a fresh install of Fedora 22, installed the google-droid-sans-fonts package, and installed your theme, but the bug still persists.

I also tried and installed your theme using openSUSE Tumbleweed in a VM and bug is not there.

With that said, do you think is the Fedora google-droid-sans-fonts package or some other theming issue with Fedora?

**Comment by zagortenay333** [comment] 2015-07-03 20:23
No clue really. I have fedora 22 as well and don't have this problem.

**Comment by mydegeneration** [comment] 2015-07-03 20:24
Where did you get your Droid Sans fonts from?

**Comment by zagortenay333** [comment] 2015-07-03 20:29
Dont' remember. Probably from the CLI

**Comment by zagortenay333** [comment] 2015-07-12 18:56
I just decided to install the google-droid-sans package from CLI and got the same problem!

Seems to be an issue with this package on fedora.

**Comment by mydegeneration** [comment] 2015-07-12 18:59
Yeah I figured something like that. Where do you recommend getting Droid Sans from then?

**Comment by zagortenay333** [comment] 2015-07-12 18:59
Just a min. I'm trying to figure out where I got it from.

**Comment by zagortenay333** [comment] 2015-07-12 19:03
OK, its from the google-fonts website: https://www.google.com/fonts

**Comment by mydegeneration** [comment] 2015-07-12 19:09
Yup, that fixed it. Thanks!
